### ISSUE TITLE
ImportError: cannot import name combinations_with_replacement

### ISSUE THREAD

**Issue by kb1sph** [mwicat/sepconf#1]
I'm running CentOS 6.8 and have installed python-setuptools and python-pip.  There is no python-wheel package that I can find to install.

When I run the command, sepconf generate 2 --phone=7960 --render=asterisk.tmpl, I get the following error.

Traceback (most recent call last):
  File "/usr/bin/sepconf", line 11, in <module>
    load_entry_point('sepconf', 'console_scripts', 'sepconf')()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 299, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2229, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1948, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "/root/src/sepconf/sepconf/main.py", line 7, in <module>
    from itertools import (combinations_with_replacement,
ImportError: cannot import name combinations_with_replacement
![pbxhost-sepconf](https://cloud.githubusercontent.com/assets/10102494/19021243/58e403b4-888b-11e6-8032-577dce8b9151.jpg)

**Comment by trolling-on-the-Moon** [comment]
your python ver is 2.6? combinations_with_replacement is in standard lib in itertools from python 2.7.
Please upgrade your python.

P.S: for those who have python 3+ and look for some solution: make sure you did not spell it wrong when imported, for example my atom suggested WRONG name (misspelled there) and I was confused for a while. Verify that you imported name correctly, letter by letter, it might save your time :D
